name: Update GitLab Activity

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  update_activity:
    runs-on: ubuntu-latest
    name: Generate and Update GitLab Activity Graph
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Generate and update activity graph
        run: python create_png.py
        env:
          GITLAB_USER_ID: ${{ secrets.GITLAB_USER_ID }}
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          GITHUB_REPO: 'remireci/gitlab_activity'
          IMPORT_GITLAB_GITHUB_TOKEN: ${{ secrets.IMPORT_GITLAB_GITHUB_TOKEN }}

      - name: Check if there are changes to commit
        id: git_status
        run: |
          changes=$(git status --porcelain)
          if [ -n "$changes" ]; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

      - name: Commit and push changes if any
        if: steps.git_status.outputs.changes == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add gitlab_activity.png
          git commit -m "Update GitLab activity graph"
          git push origin main
        env:
          IMPORT_GITLAB_GITHUB_TOKEN: ${{ secrets.IMPORT_GITLAB_GITHUB_TOKEN }}
