name: Update GitLab Activity

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  update_activity:
    runs-on: ubuntu-latest
    name: Generate and Update GitLab Activity Graph
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Generate and update activity graph
        run: python create_png.py
        env:
          GITLAB_USER_ID: ${{ secrets.GITLAB_USER_ID }}
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          GITHUB_REPO: ''
          IMPORT_GITLAB_GITHUB_TOKEN: ${{ secrets.IMPORT_GITLAB_GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add gitlab_activity.png README.md
          git commit -m "Update GitLab activity graph"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Update README
      #   if: success()
      #   run: python update_readme.py
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
