name: Update GitLab Activity

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  update_activity:
    runs-on: ubuntu-latest
    name: Generate and Update GitLab Activity Graph
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main  # Ensure you are on the main branch

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Generate and update activity graph
        id: generate_activity
        run: python create_png.py
        env:
          GITLAB_USER_ID: ${{ secrets.GITLAB_USER_ID }}
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          GITHUB_REPO: 'remireci/gitlab_activity'
          IMPORT_GITLAB_GITHUB_TOKEN: ${{ secrets.IMPORT_GITLAB_GITHUB_TOKEN }}

      - name: Commit and push changes
        if: steps.generate_activity.outcome == 'success'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git stash  # Stash any local changes
          git pull origin main  # Pull the latest changes from the remote repository
          git stash pop || echo "No stashed changes to apply"  # Apply the stashed changes
          git add gitlab_activity.png
          git commit -m "Update GitLab activity graph" || echo "No changes to commit"
          git push origin main
        env:
          IMPORT_GITLAB_GITHUB_TOKEN: ${{ secrets.IMPORT_GITLAB_GITHUB_TOKEN }}
